CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Increase transmission strength.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_OLED_ON=y
CONFIG_NICE_EPAPER_ON=n
CONFIG_NICE_OLED_WIDGET_INVERTED=y
CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_SLEEP=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=y

CONFIG_ZMK_KEYBOARD_NAME="Edy_Chocofi"
